-- sql script to generate table user
create table users
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password varchar(255) not null,
    username varchar(255) not null
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table users
    owner to postgres;

-- sql script to generate table user_roles
create table user_roles
(
    user_id bigint not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references users,
    roles   varchar(255)
        constraint user_roles_roles_check
            check ((roles)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[]))
);

alter table user_roles
    owner to postgres;

-- sql script to generate table record
create table record
(
    id         bigint generated by default as identity
        primary key,
    end_time   timestamp(6),
    project_id bigint,
    start_time timestamp(6),
    user_id    bigint
);

alter table record
    owner to postgres;

-- sql script to generate table project
create table project
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    name        varchar(255)
);

alter table project
    owner to postgres;